/**
 * API Endpoints
 *
 * All endpoint base paths in one place.
 * Generated by zakarya — add new endpoints here or run:
 *   zakarya generate feature <name>
 */

export const ENDPOINTS = {
  // [zakarya:inject:endpoints]
  ASSIGNMENTS_BASE: '/assignments',
  PUBLICATIONS_BASE: '/publications',
  NOTIFICATIONS_BASE: '/notifications',
  DASHBOARD_BASE: '/dashboard/summary',
  CATEGORIES_BASE: '/categories',
  AUTH_BASE: '/auth',
  USERS_BASE: '/users',
  ARTICLES_BASE: '/articles',
  AUTH: '/auth',
} as const;

export type EndpointKey = keyof typeof ENDPOINTS;
