import type { Metadata } from 'next';
import { QueryProvider } from '@/shared/tanstack/providers';
import { primaryFont, academicFont, monoFont } from '@/shared/fonts/fonts';
import './globals.css';

export const metadata: Metadata = {
  title: 'frontend',
  description: 'Generated by zakarya',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={`${primaryFont.variable} ${academicFont.variable} ${monoFont.variable} font-primary`}
      >
        <QueryProvider>{children}</QueryProvider>
      </body>
    </html>
  );
}
