export default function HomePage() {
  return (
    <main style={{ padding: '2rem', fontFamily: 'system-ui, sans-serif' }}>
      <h1>Welcome to <strong>frontend</strong></h1>
      <p>Generated by <code>zakarya</code> — Next.js App Router + TanStack Query + Axios</p>
      <ul>
        <li>Add features: <code>zakarya generate feature &lt;name&gt;</code></li>
        <li>Add CRUD resource: <code>zakarya generate resource &lt;name&gt;</code></li>
      </ul>
    </main>
  );
}
